#price1_child=float(input('how much for child meal? ')
print()
price1_child=float(input('How much for child drink? '))
price2_adult=float(input('How much for adult drink? '))
nu1_of_children=int(input('How many children do you have? '))
nu2_of_adult=int(input('How many adults are here in number? '))
print()
sale_tax=float(input('What is the sale tax rate? '))
print(f'Subtotal :$ {price1_child * nu1_of_children + price2_adult*nu2_of_adult}')
print(price1_child * nu1_of_children + price2_adult * nu2_of_adult/price1_child + price2_adult )
print()
payment=float(input('What is the payment amount? '))
print(f'Change: ${sale_tax/payment}')
print() 